# Generated by Django 3.0.3 on 2020-05-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaving_From', models.CharField(choices=[('Agra-Central Office', 'Agra-Central Office'), ('Almena - Central Office', 'Almena - Central Office'), ('Alton-Central Office', 'Alton-Central Office'), ('Athol - Central Office', 'Althol - Central Office')], default=None, max_length=40)),
                ('heading_To', models.CharField(choices=[('Agra-Central Office', 'Agra-Central Office'), ('Almena - Central Office', 'Almena - Central Office'), ('Alton-Central Office', 'Alton-Central Office'), ('Athol - Central Office', 'Althol - Central Office')], default=None, max_length=40)),
                ('leaving_By', models.DateTimeField(max_length=40)),
                ('returning_By', models.DateTimeField(max_length=40)),
            ],
        ),
    ]
