# Generated by Django 3.0.3 on 2020-05-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0022_auto_20200501_1111'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='vehicle.Vehicle'),
            preserve_default=False,
        ),
    ]
