# Generated by Django 3.0.3 on 2020-02-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.IntegerField(max_length=10)),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
