# Generated by Django 3.0.3 on 2020-02-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20200225_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehicle_models',
        ),
    ]
