# Generated by Django 3.0.3 on 2020-02-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20200225_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle_models',
            new_name='Vehicle',
        ),
    ]
