# Generated by Django 3.0.3 on 2020-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20200304_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_Number', models.IntegerField()),
                ('employee', models.CharField(choices=[('emp 1', 'Emp 1'), ('emp 2', 'Emp 2'), ('emp 3', 'Emp 3')], max_length=255)),
                ('make', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=40)),
                ('year', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('current_Mileage', models.IntegerField()),
                ('mileage_year', models.IntegerField()),
                ('mileage_period', models.IntegerField()),
                ('last_Oil_Change', models.IntegerField()),
            ],
        ),
    ]
