# Generated by Django 3.0.3 on 2020-03-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_maintenance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='mileage_period',
            new_name='mileage_Period',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='mileage_year',
            new_name='mileage_Year',
        ),
    ]
