# Generated by Django 3.0.3 on 2020-04-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20200331_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='make',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='model',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='vehicle_Number',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='year',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='vehicle.Vehicle'),
            preserve_default=False,
        ),
    ]
