# Generated by Django 3.0.3 on 2020-04-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_auto_20200402_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='current_Mileage',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='last_Oil_Change',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='mileage_Period',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='mileage_Year',
        ),
    ]
