# Generated by Django 3.0.3 on 2020-04-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20200402_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('maintenance_Date', models.DateField(max_length=40)),
                ('changed_Oil', models.BooleanField()),
                ('rotated_Tires', models.BooleanField()),
                ('changed_Transmission_Fluid', models.BooleanField()),
                ('comments', models.CharField(max_length=255)),
            ],
        ),
    ]
