# Generated by Django 3.0.3 on 2020-04-02 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_addmaintenance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddMaintenance',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='changed_Oil',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='changed_Transmission_Fluid',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='mileage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='rotated_Tires',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
