# Generated by Django 3.0.3 on 2020-04-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20200402_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=255)),
                ('month', models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=255)),
                ('month_End_Mileage', models.IntegerField(max_length=40)),
                ('first_Aid_Kit_Status', models.BooleanField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40)),
                ('fire_Extinguisher_Status', models.BooleanField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40)),
                ('drugalcohol_Testing_Kit_Status', models.BooleanField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_Date',
            field=models.IntegerField(max_length=40),
        ),
    ]
