# Generated by Django 3.0.3 on 2020-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0013_auto_20200413_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='drugalcohol_Testing_Kit_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='fire_Extinguisher_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='first_Aid_Kit_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], max_length=40),
        ),
    ]
