# Generated by Django 3.0.3 on 2020-04-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20200413_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.Mileage'),
            preserve_default=False,
        ),
    ]
