# Generated by Django 3.0.3 on 2020-04-14 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_mileage_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_entry', to='vehicle.Vehicle'),
        ),
    ]
