# Generated by Django 3.0.3 on 2020-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_auto_20200414_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='drugalcohol_Testing_Kit_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='fire_Extinguisher_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='first_Aid_Kit_Status',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad')], default=None, max_length=40),
        ),
    ]
