# Generated by Django 3.0.3 on 2020-04-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0019_auto_20200429_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='mileage',
            name='no_Days_Commuted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
