# Generated by Django 3.0.3 on 2020-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_mileage_no_days_commuted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='month',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '1'), (12, '12')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mileage',
            name='year',
            field=models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], max_length=255),
        ),
    ]
