# Generated by Django 3.0.3 on 2020-05-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0021_auto_20200430_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mileage',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Mileage',
        ),
    ]
